# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array1=np.array([123,34,987,30,15])
print(array1)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
a=np.sort(array1)
print(a)


[123  34 987  30  15]
[ 15  30  34 123 987]


# Problem 2

In [18]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
array2=np.array([10,15,30,45,60])
print(array2)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
array3=np.arange(6,15)
print(array3)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
array4=np.arange(50,100,5)
print(array4)


# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
array_zero=np.zeros(10)
print(array_zero)


# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
array_ones=np.ones(10)
print(array_ones)


# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
array5=np.arange(1,100,20)
print(array5)


# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
d=np.random.randint(10,31,5)
print(d)

# 8- [-1 ile 1] arasında 10 adet sayı üretin..........................................................
r=np.random.uniform(-1,1,10)
print(r)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
n=np.random.randint(10,51,size=(3,5))
print(n)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
row_sums=n.sum(axis=1)
column_sums=n.sum(axis=0)
print(f"satır toplamı:{row_sums}")
print(f"sütun toplamı:{column_sums}")

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
maxValue=n.max()
minValue=n.min()
meanValue=n.mean()
print("max:",maxValue)
print("min:",minValue)
print("mean:",meanValue)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_index=np.unravel_index(n.argmax(),n.shape)
print(max_index)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
dizi=np.arange(10,20).reshape(2,5)
ilk_üç=dizi[:3]
print(ilk_üç)

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
reversed=dizi[::-1]
print(reversed)

# 15- Üretilen matrisin ilk satırını seçiniz.
first_row=dizi[0,:]
print(first_row)
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
eleman=dizi[1,2]
print(eleman)
# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
first_all_rows=dizi[:,0]
print(first_all_rows)
# 18- Üretilen matrisin her bir elemanının karesini alınız.
kareleri=dizi**2
print(kareleri)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
new_matrixx=np.arange(-50,50).reshape(10,10)
filtered_matrixx=new_matrixx[(new_matrixx%2==0) & (new_matrixx>0)]
print(filtered_matrixx)


[10 15 30 45 60]
[ 6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1 21 41 61 81]
[30 17 14 10 17]
[ 0.45576856  0.61597306  0.71750477  0.02569006  0.03489371  0.7665632
  0.62304214 -0.94909366  0.17559186 -0.99145075]
[[23 28 28 29 35]
 [42 46 42 33 16]
 [17 33 28 34 13]]
satır toplamı:[143 179 125]
sütun toplamı:[ 82 107  98  96  64]
max: 46
min: 13
mean: 29.8
(1, 1)
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[15 16 17 18 19]
 [10 11 12 13 14]]
[10 11 12 13 14]
17
[10 15]
[[100 121 144 169 196]
 [225 256 289 324 361]]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
