# Problem 1

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matrix=np.random.randint(1,11,size=5)
print(matrix)

# 3 - matris'in boyutunu öğrenin
dimension=matrix.shape
print(dimension)

# 4 - matris'i yeniden boyutlandırın
x=matrix.reshape(5,1)
print(x)

# 5 - matris'in boyut sayısını öğrenin
print(x.ndim)


[10  6  3  1  8]
(5,)
[[10]
 [ 6]
 [ 3]
 [ 1]
 [ 8]]
2


# Problem 2

In [25]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
odd_numbers=np.arange(1,10,2)
print(odd_numbers)
matris=odd_numbers.reshape(5,1)
print(matris)

# 2 - Oluşturduğunuz matrisi parçalayın
submatrix=matris[:3,:]
print(submatrix)
# 3 - Parçalanmış matrisleri birleştirin
united_matrix=np.vstack((submatrix,matris[3:,:]))
print(united_matrix)

[1 3 5 7 9]
[[1]
 [3]
 [5]
 [7]
 [9]]
[[1]
 [3]
 [5]]
[[1]
 [3]
 [5]
 [7]
 [9]]


# Problem 3

In [28]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
random_numbers=np.random.choice((np.arange(5,100,2)), size=10)
print(random_numbers)
m=random_numbers.reshape(2,5)
print(m)
# 2 - matris'in özelliklerini inceleyin
print(m.shape)
print(m.ndim)
print(m.size)


[67 73 23 39 37 15 49 29 19 27]
[[67 73 23 39 37]
 [15 49 29 19 27]]
(2, 5)
2
10
